### ISSUE TITLE
Yolo v9 license and docker exist?

### ISSUE THREAD

**Issue by kdhRGT** [WongKinYiu/YOLO#50]
Hello author

This is great and interesting work.

I have questions. I found other yolov9 repo on github.

But this is similar with this repo but license is different, the other repo url on below:

[https://github.com/WongKinYiu/yolov9](https://github.com/WongKinYiu/yolov9)

Can you help me what is real license on yolov9 ?

second question is

Do you have docker image in docker hub?

**Comment by CyprienQuemeneur** [comment]
(Not an author of this repository and not legal advice.) Hi, the link you provided corresponds to the original implementation of YOLOv9, which itself corresponds to the paper "YOLOv9: Learning What You Want to Learn Using Programmable Gradient Information" and is licensed under the GPL-3.0 license. All the most recent YOLO variants use a strong copyleft license like GPL-3.0 (v6, v7, v9...) and AGPL-3.0 (v5, v8, v10...). This repository is an ongoing effort to reimplement YOLOv7 and YOLOv9 under a more permissive open-source license. If I am not mistaken, the authors started from the YOLOX codebase, which is the most recent variant of YOLO to have a permissive license.

**Comment by chilin0525** [comment]
Check these two issue related to License of original YOLOv9 repo:
* https://github.com/WongKinYiu/yolov9/issues/10
* https://github.com/WongKinYiu/yolov9/issues/82

**Comment by henrytsui000** [comment]
Hi kdhRGT,

- As mentioned above, YOLOv9 is a paper, so there is no license associated with it. This repository is a paper implementation licensed under the MIT License

- Additionally, the name `yolo` is already registered on DockerHub, which is why the image isn't available there under that name. I have pushed an image [here](https://hub.docker.com/repository/docker/henrytsui000/yolo/general), but please note that the code is not stable yet. Once a new name is determined, we will upload the image to DockerHub and PyPI.

Thank you for your understanding and patience.

Best regards,
Henry Tsui

**Comment by kdhRGT** [comment]
Thank you so much about all reply ~!

Now I can understand well about history now.

Best regards.
